# Background and foreground colors
background = #1c2023
foreground = #c7ccd1

# Standard colors
palette = 0=#1c2023
palette = 1=#cf867c
palette = 2=#95c7ae
palette = 3=#aec795
palette = 4=#6f8aad
palette = 5=#aa5b82
palette = 6=#73899f
palette = 7=#c7ccd1

# Bright colors
palette = 8=#747c84
palette = 9=#cf867c
palette = 10=#95c7ae
palette = 11=#aec795
palette = 12=#6f8aad
palette = 13=#aa5b82
palette = 14=#73899f
palette = 15=#f3f4f5
