$color = rgba(28, 32, 35, 1)
$inner_color = rgba(28, 32, 35, 0.66)
$outer_color = rgba(170, 91, 130, 1)
$font_color = rgba(199, 204, 209, 1)
$placeholder_color = rgba(199, 204, 209, 0.7)
$check_color = rgba(115, 137, 159, 1)
